# tpcds_queue_updates.py
# Generated by Perplexity.ai
import duckdb
from multiprocessing import Process, Queue

def reader(queue):
    conn = duckdb.connect('md:tpcds_copy10')
    result = conn.execute("SELECT * FROM inventory limit 1000")
    for row in result.fetchall():
        queue.put(row)
    queue.put(None)  # Signal end of data
    conn.close()

def writer(queue):
    conn = duckdb.connect('md:tpcds')
    while True:
        row = queue.get()
        if row is None:
            break
        conn.execute("INSERT INTO inventory VALUES (?, ?, ?, ?)", row)
    conn.close()

if __name__ == '__main__':
    data_queue = Queue()
    
    reader_process = Process(target=reader, args=(data_queue,))
    writer_process = Process(target=writer, args=(data_queue,))
    
    reader_process.start()
    writer_process.start()
    
    reader_process.join()
    writer_process.join()
